version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mindgateway
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: mindgateway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  etcd:
    image: quay.io/coreos/etcd:v3.5.11
    command: >
      etcd
      --advertise-client-urls http://0.0.0.0:2379
      --listen-client-urls http://0.0.0.0:2379
    ports:
      - "2379:2379"

  # Mock Ollama for local development
  ollama-mock:
    image: nginx:alpine
    volumes:
      - ./test/mocks/ollama:/usr/share/nginx/html
    ports:
      - "11434:80"

volumes:
  postgres_data: