version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mindgateway_test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mindgateway_test
    ports:
      - "5433:5432"
    tmpfs: 
      - /var/lib/postgresql/data

  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  etcd-test:
    image: quay.io/coreos/etcd:v3.5.11
    command: >
      etcd
      --advertise-client-urls http://0.0.0.0:2379
      --listen-client-urls http://0.0.0.0:2379
    ports:
      - "2380:2379"

  integration-tests:
    build:
      context: .
      dockerfile: test/Dockerfile.test
    depends_on:
      - postgres-test
      - redis-test
      - etcd-test
    environment:
      - TEST_POSTGRES_URI=postgres://mindgateway_test:test@postgres-test:5432/mindgateway_test?sslmode=disable
      - TEST_REDIS_URI=redis://redis-test:6379/0
      - TEST_ETCD_ENDPOINTS=etcd-test:2379
    volumes:
      - ./:/app
    command: go test -v ./test/integration/...