# Default values for MindGateway Helm chart

global:
  environment: prod
  image:
    registry: ghcr.io
    repository: company/mindgateway
    tag: latest
    pullPolicy: IfNotPresent
  imagePullSecrets: []

# Namespace configuration
namespace:
  create: true
  name: mindgateway

# Gateway configuration
gateway:
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    hosts:
      - host: api.mindgateway.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: mindgateway-tls-cert
        hosts:
          - api.mindgateway.example.com

# Auth service configuration
auth:
  replicaCount: 2
  service:
    type: ClusterIP
    port: 9091
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Registry service configuration
registry:
  replicaCount: 2
  service:
    type: ClusterIP
    port: 9092
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Database configuration
database:
  # Use external database (if false, will deploy a Postgres instance)
  external: false
  host: "mindgateway-db"
  port: 5432
  name: "mindgateway"
  username: "mindgateway"
  # password should be provided through values-secret.yaml
  password: ""
  sslMode: "require"

# Redis configuration
redis:
  # Use external Redis (if false, will deploy a Redis instance)
  external: false
  host: "mindgateway-redis"
  port: 6379
  # password should be provided through values-secret.yaml
  password: ""
  db: 0

# ETCD configuration
etcd:
  # Use external ETCD (if false, will deploy an ETCD instance)
  external: false
  endpoints:
    - "mindgateway-etcd:2379"
  # username and password should be provided through values-secret.yaml
  username: ""
  password: ""

# Secret configuration
secrets:
  # JWT secret should be provided through values-secret.yaml
  jwtSecret: ""

# Config settings
config:
  logLevel: "info"
  shutdownTimeout: 30

metrics:
  enabled: true
  serviceMonitor:
    enabled: false