apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindgateway-auth
  namespace: mindgateway
  labels:
    app: mindgateway
    component: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindgateway
      component: auth
  template:
    metadata:
      labels:
        app: mindgateway
        component: auth
    spec:
      containers:
      - name: auth
        image: ${REGISTRY}/mindgateway/auth:${TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
          name: grpc
        envFrom:
        - configMapRef:
            name: mindgateway-config
        - secretRef:
            name: mindgateway-secrets
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi