apiVersion: v1
kind: Service
metadata:
  name: mindgateway-auth
  namespace: mindgateway
  labels:
    app: mindgateway
    component: auth
spec:
  type: ClusterIP
  ports:
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: grpc
  selector:
    app: mindgateway
    component: auth