# Production configuration for MindGateway

# General settings
environment: "prod"
log_level: "info"
shutdown_timeout: 30s

# Server settings
server:
  address: "0.0.0.0"
  port: 8080

# Database settings
database:
  host: "${DB_HOST}"
  port: ${DB_PORT}
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  name: "${DB_NAME}"
  ssl_mode: "require"

# Redis settings
redis:
  host: "${REDIS_HOST}"
  port: ${REDIS_PORT}
  password: "${REDIS_PASSWORD}"
  db: 0

# ETCD settings
etcd:
  endpoints:
    - "${ETCD_ENDPOINTS}"
  username: "${ETCD_USERNAME}"
  password: "${ETCD_PASSWORD}"

# Service specific settings
auth:
  address: "${AUTH_SERVICE_ADDRESS}"
  jwt_secret: "${JWT_SECRET}"

registry:
  address: "${REGISTRY_SERVICE_ADDRESS}"

# Worker settings
worker:
  connect_timeout: 5s
  request_timeout: 60s
  health_check_period: 30s

# Queue settings
queue:
  max_size: 10000
  default_priority: 5
  processing_period: 100ms