apiVersion: v1
kind: Service
metadata:
  name: mindgateway-registry
  namespace: mindgateway
  labels:
    app: mindgateway
    component: registry
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: grpc
  selector:
    app: mindgateway
    component: registry